<a href="https://colab.research.google.com/github/maykends/-Data_science_studies/blob/main/292_Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrizes

Em Python, uma matriz é uma coleção ordenada de valores que podem ser de diferentes tipos de dados, como inteiros, floats, strings, etc. Ela é representada por colchetes [] e os valores são separados por vírgulas.

In [2]:
import numpy as np # biblioteca para processamento cientifico para funções estatistica

In [3]:
# array é uma lista um pouco mais elaborada e mais rápida
matriz = np.array([[2,3,1],
                   [4,5,7]]) # definindo linhas e colunas 2 X 3 = Linhas X colunas

In [5]:
matriz

array([[2, 3, 1],
       [4, 5, 7]])

In [6]:
print(matriz)

[[2 3 1]
 [4 5 7]]


In [8]:
matriz.shape # retorna o tipo ou formato da matriz, como 2 linhas e 3 colunas

(2, 3)

In [9]:
matriz[1] # retorno da segunda linha

array([4, 5, 7])

In [10]:
matriz[0][0] # retorno a linha e coluna zero

2

In [12]:
matriz[0][1] # retorno a linha 0 e coluna 2

3

In [14]:
matriz[0][2] # retorno a linha 0 e coluna 3

1

In [15]:
matriz[1][0] # retorno a linha 1 e coluna 1

4

In [18]:
matriz[1][1] # retorno a linha 2 e coluna 2

5

In [ ]:
# percorre todos os elementos em uma matriz

In [20]:
matriz.shape 

(2, 3)

In [28]:
# percorrendo todos os elementos da matriz
for i in range(matriz.shape[0]): # percorrendo a linha da matriz
  print(matriz[i]) # retorna as linhas da matriz
  for j in range(matriz.shape[1]): # percorrendo a coluna da matriz
    print(matriz[i][j]) # acessa cada elemento da coluna [2 3 1] e [4 5 7]

[2 3 1]
2
3
1
[4 5 7]
4
5
7
